import { PDMTable, PDMColumn, PDMKey, PDMReference } from '../../main/services/pdm-parser';

export interface DBMSInfo {
  code: string;
  name: string;
  version?: string;
}

// 生成CREATE TABLE SQL（含主键、外键、索引）
export function generateCreateTableSQL(table: PDMTable, dbms?: DBMSInfo, references?: PDMReference[], allTables?: PDMTable[]): string {
  const dialect = normalizeDialect(dbms?.code);
  const lines: string[] = [];

  // 列定义
  const colDefs = table.columns.map(col => generateColumnDef(col, dialect));

  // 主键约束（内联）
  if (table.primaryKey && table.primaryKey.columnRefs.length > 0) {
    const pkCols = resolveColumnCodes(table, table.primaryKey.columnRefs, dialect);
    if (pkCols.length > 0) {
      const pkName = quoteIdentifier(`PK_${table.code}`, dialect);
      colDefs.push(`  CONSTRAINT ${pkName} PRIMARY KEY (${pkCols.join(', ')})`);
    }
  }

  // 外键约束（内联）
  const fkConstraints = getForeignKeyConstraints(table, references, allTables, dialect);
  for (const fk of fkConstraints) {
    colDefs.push(`  CONSTRAINT ${fk.name} FOREIGN KEY (${fk.columns}) REFERENCES ${fk.refTable} (${fk.refColumns})`);
  }

  // MySQL: 表注释放在CREATE TABLE末尾
  const tableCommentSuffix = (dialect === 'mysql' && table.comment)
    ? ` COMMENT = '${escapeSqlString(table.comment)}'`
    : '';

  lines.push(`CREATE TABLE ${quoteIdentifier(table.code, dialect)} (`);
  lines.push(colDefs.join(',\n'));
  lines.push(`)${tableCommentSuffix};`);

  // 非MySQL: 表注释用COMMENT ON TABLE
  if (dialect !== 'mysql' && table.comment) {
    lines.push(generateTableComment(table, dialect));
  }

  // 列注释
  const colComments = table.columns
    .filter(c => c.comment)
    .map(c => generateColumnComment(table.code, c, dialect));
  if (colComments.length > 0) {
    lines.push(colComments.join('\n'));
  }

  // 索引（CREATE INDEX）
  const indexStatements = generateIndexStatements(table, dialect);
  if (indexStatements.length > 0) {
    lines.push('');
    lines.push(indexStatements.join('\n'));
  }

  lines.push('');
  return lines.join('\n');
}

// 生成所有表的SQL
export function generateAllTablesSQL(tables: PDMTable[], dbms?: DBMSInfo, references?: PDMReference[]): string {
  const dialect = normalizeDialect(dbms?.code);
  let header = '';
  if (dbms) {
    header = `-- Database: ${dbms.name || dbms.code}${dbms.version ? ` ${dbms.version}` : ''}\n`;
  }
  header += `-- Generated by PDM Reader\n\n`;
  return header + tables.map(t => generateCreateTableSQL(t, dbms, references, tables)).join('\n');
}

function normalizeDialect(code?: string): string {
  if (!code) return 'generic';
  const lower = code.toLowerCase();
  if (lower.includes('mysql') || lower.includes('mariadb')) return 'mysql';
  if (lower.includes('postgres')) return 'postgresql';
  if (lower.includes('oracle')) return 'oracle';
  if (lower.includes('sql server') || lower.includes('mssql')) return 'sqlserver';
  if (lower.includes('sqlite')) return 'sqlite';
  return 'generic';
}

function quoteIdentifier(name: string, dialect: string): string {
  if (dialect === 'mysql') return `\`${name}\``;
  if (dialect === 'postgresql' || dialect === 'oracle') return `"${name}"`;
  if (dialect === 'sqlserver') return `[${name}]`;
  return `"${name}"`; // generic
}

function mapDataType(col: PDMColumn, dialect: string): string {
  let type = col.dataType;

  if (dialect === 'oracle') {
    const upper = type.toUpperCase();
    if (upper === 'INT' || upper === 'INTEGER') return 'NUMBER(10)';
    if (upper === 'BIGINT') return 'NUMBER(19)';
    if (upper === 'SMALLINT') return 'NUMBER(5)';
    if (upper === 'TINYINT') return 'NUMBER(3)';
    if (upper === 'DATETIME' || upper === 'TIMESTAMP') return 'TIMESTAMP';
    if (upper === 'TEXT' || upper === 'CLOB') return 'CLOB';
    if (upper === 'BLOB') return 'BLOB';
    if (upper === 'BOOLEAN' || upper === 'BOOL') return 'NUMBER(1)';
  }

  if (dialect === 'sqlserver') {
    const upper = type.toUpperCase();
    if (upper === 'BOOLEAN' || upper === 'BOOL') return 'BIT';
    if (upper === 'TEXT') return 'NVARCHAR(MAX)';
    if (upper === 'CLOB') return 'NVARCHAR(MAX)';
    if (upper === 'BLOB') return 'VARBINARY(MAX)';
  }

  if (dialect === 'mysql') {
    const upper = type.toUpperCase();
    if (upper === 'BOOLEAN' || upper === 'BOOL') return 'TINYINT(1)';
  }

  if (dialect === 'postgresql') {
    const upper = type.toUpperCase();
    if (upper === 'BOOLEAN' || upper === 'BOOL') return 'BOOLEAN';
    if (upper === 'CLOB') return 'TEXT';
    if (upper === 'BLOB') return 'BYTEA';
  }

  return type;
}

function generateColumnDef(col: PDMColumn, dialect: string): string {
  const dataType = mapDataType(col, dialect);
  let def = `  ${quoteIdentifier(col.code, dialect)} ${dataType}`;

  if (col.identity) {
    if (dialect === 'mysql') def += ' AUTO_INCREMENT';
    else if (dialect === 'sqlserver') def += ' IDENTITY(1,1)';
    else if (dialect === 'postgresql') def += ' GENERATED ALWAYS AS IDENTITY';
  }

  if (!col.nullable && !col.identity) {
    def += ' NOT NULL';
  }

  if (col.defaultValue && !col.identity) {
    def += ` DEFAULT ${col.defaultValue}`;
  }

  if (dialect === 'mysql' && col.comment) {
    def += ` COMMENT '${escapeSqlString(col.comment)}'`;
  }

  return def;
}

// 解析列引用为带引号的列code
// refs可能是列code（已解析）或列ID（未解析）
function resolveColumnCodes(table: PDMTable, refs: string[], dialect: string): string[] {
  return refs
    .map(ref => {
      // 先按code匹配
      const colByCode = table.columns.find(c => c.code === ref);
      if (colByCode) return quoteIdentifier(colByCode.code, dialect);
      // 再按id匹配
      const colById = table.columns.find(c => c.id === ref);
      if (colById) return quoteIdentifier(colById.code, dialect);
      // 如果都没匹配到，直接用ref作为列名
      return quoteIdentifier(ref, dialect);
    });
}

// 获取外键约束 - 直接使用PDMReference，不依赖table.keys
interface FKConstraint {
  name: string;
  columns: string;
  refTable: string;
  refColumns: string;
}

function getForeignKeyConstraints(table: PDMTable, references?: PDMReference[], allTables?: PDMTable[], dialect?: string): FKConstraint[] {
  if (!references || !allTables) return [];
  const d = dialect || 'generic';
  const constraints: FKConstraint[] = [];

  // 找到当前表作为child表的所有reference
  const childRefs = references.filter(r =>
    r.childTableId === table.id || r.childTableCode === table.code
  );

  for (const ref of childRefs) {
    // 外键列（child端）
    const childCols = ref.childColumnCodes && ref.childColumnCodes.length > 0
      ? ref.childColumnCodes.map(c => quoteIdentifier(c, d))
      : [];
    if (childCols.length === 0) continue;

    // 被引用表
    const parentTable = allTables.find(t => t.id === ref.parentTableId || t.code === ref.parentTableCode);
    if (!parentTable) continue;

    // 被引用列（parent端）
    const parentCols = ref.parentColumnCodes && ref.parentColumnCodes.length > 0
      ? ref.parentColumnCodes.map(c => quoteIdentifier(c, d))
      : [];
    if (parentCols.length === 0) continue;

    // 使用reference的code作为FK名称（PDM中已定义）
    const fkName = quoteIdentifier(ref.code || `FK_${table.code}_${parentTable.code}`, d);
    constraints.push({
      name: fkName,
      columns: childCols.join(', '),
      refTable: quoteIdentifier(parentTable.code, d),
      refColumns: parentCols.join(', ')
    });
  }

  return constraints;
}

// 生成索引语句
function generateIndexStatements(table: PDMTable, dialect: string): string[] {
  const statements: string[] = [];
  const tableName = quoteIdentifier(table.code, dialect);

  for (const idx of (table.indexes || [])) {
    // 跳过主键索引（已在CREATE TABLE中定义）
    if (idx.code === table.primaryKey?.code || idx.name === table.primaryKey?.name) continue;

    const idxName = quoteIdentifier(idx.code || `IDX_${table.code}_${idx.columnRefs.join('_')}`, dialect);

    if (idx.columnRefs.length > 0) {
      const colList = idx.columnRefs.map(c => quoteIdentifier(c, dialect)).join(', ');
      let sql = 'CREATE ';
      if (idx.unique) sql += 'UNIQUE ';
      if (idx.cluster && (dialect === 'sqlserver' || dialect === 'generic')) sql += 'CLUSTERED ';
      sql += `INDEX ${idxName} ON ${tableName} (${colList});`;
      statements.push(sql);
    } else {
      // 索引没有列信息，生成注释提示
      statements.push(`-- 索引 ${idx.code}（缺少列信息，请手动补充）`);
    }
  }

  return statements;
}

function generateTableComment(table: PDMTable, dialect: string): string {
  const escaped = escapeSqlString(table.comment || '');
  const tableName = quoteIdentifier(table.code, dialect);

  if (dialect === 'mysql') return '';

  if (dialect === 'sqlserver') {
    return `EXEC sp_addextendedproperty 'MS_Description', '${escaped}', 'SCHEMA', 'dbo', 'TABLE', '${table.code}';`;
  }

  return `COMMENT ON TABLE ${tableName} IS '${escaped}';`;
}

function generateColumnComment(tableCode: string, col: PDMColumn, dialect: string): string {
  if (!col.comment) return '';
  const escaped = escapeSqlString(col.comment);
  const tableName = quoteIdentifier(tableCode, dialect);
  const colName = quoteIdentifier(col.code, dialect);

  if (dialect === 'mysql') return '';

  if (dialect === 'sqlserver') {
    return `EXEC sp_addextendedproperty 'MS_Description', '${escaped}', 'SCHEMA', 'dbo', 'TABLE', '${tableCode}', 'COLUMN', '${col.code}';`;
  }

  return `COMMENT ON COLUMN ${tableName}.${colName} IS '${escaped}';`;
}

function escapeSqlString(s: string): string {
  return s.replace(/'/g, "''");
}
